# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proxies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sourceid', models.IntegerField()),
                ('proxy', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('countrycode', models.CharField(max_length=10)),
                ('booking', models.IntegerField()),
                ('expedia', models.IntegerField()),
                ('google', models.IntegerField()),
                ('mmt', models.IntegerField()),
                ('ports', models.IntegerField()),
            ],
        ),
    ]
